services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    ports:
      - "3012:3000"
    volumes:
      - sqlite_data:/app/data
    env_file:
      - ./backend/.env  
    environment:
      DATABASE_URL: "file:/app/data/prod.db"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  sqlite_data: