

name: My first CI/CD pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  deploy-studybase:
    runs-on: ubuntu-latest
    env:
      SSH_OPTS: >-
        -o ServerAliveInterval=60
        -o ServerAliveCountMax=60
    steps:

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      
      - name: Pull latest changes on server
        run: |
          ssh $SSH_OPTS ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd /var/www/StudyBase
            git pull origin main
          EOF


      - name: Copy frontend env file to server
        run: |
          ssh $SSH_OPTS ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e

            cd /var/www/StudyBase/frontend

            printf '%s\n' \
              "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" \
              "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" \
              > .env
          EOF

      - name: Copy backend env file to server
        run: |
          ssh $SSH_OPTS ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            
            cd /var/www/StudyBase/backend

            printf '%s\n' \
              "CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}" \
              "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" \
              "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
              "NODE_ENV=production" \
              "PORT=${{ secrets.PORT }}" \
              "SECRET_KEY=${{ secrets.SECRET_KEY }}" \
              > .env
          EOF

      - name: Restart application using Docker Compose
        run: |
          ssh $SSH_OPTS ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd /var/www/StudyBase
            docker compose down
            docker compose up --build -d
          EOF