

name: My first CI/CD pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (workspaces)
        run: npm install

      - name: Build shared
        run: npm run build --workspace=shared

      - name: Generate Prisma client (backend)
        run: npm run prisma:generate --workspace=backend

      - name: Build backend
        run: npm run build --workspace=backend

      - name: Build frontend
        run: npm run build --workspace=frontend

  shared:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies (workspaces)
        run: npm install

      - name: Install dependencies (shared)
        run: npm install
        working-directory: ./shared

      - name: Build shared
        run: npm run build 
        working-directory: ./shared

      - name: Upload shared artifact
        uses: actions/upload-artifact@v3
        with:
          name: shared
          path: ./shared/dist
          retention-days: 1

  backend:
    runs-on: ubuntu-latest
    needs: shared

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download shared artifact
        uses: actions/download-artifact@v3
        with:
          name: shared

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies (backend)
        run: npm install
        working-directory: ./backend

      - name: Generate Prisma client
        run: npx prisma generate 
        working-directory: ./backend

      - name: Build backend
        run: npm run build
        working-directory: ./backend

  frontend:
    runs-on: ubuntu-latest
    needs: shared

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download shared artifact
        uses: actions/download-artifact@v3
        with:
          name: shared

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      



      

      